version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - pip install uv
    install:
      - uv pip install -e ".[dishka,redis]" --group=docs -p $READTHEDOCS_VIRTUALENV_PATH/bin/python

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
